//! Small debug helper for inspecting a constructed regcmd stream --
//! decodes each RegCmd's (domain, offset, value) and resolves offset
//! to its REG_* name from rkt_registers.h, so a binary's constructed
//! stream can be read/diffed against an externally-decoded one (e.g.
//! the conv.rknn regcmd decode in rknpu-spelunking/NOTES.md) without
//! hand-translating hex offsets back to register names each time.
//!
//! register_name()'s table is generated from rkt_registers.h's
//! `#define REG_*` lines (Python one-liner, not hand-transcribed --
//! see rknpu-spelunking session notes if it needs regenerating after
//! rkt_registers.h changes).

use crate::rocket::builders::RegCmd;

pub fn decode(cmd: &RegCmd) -> (u32, u32, u32) {
    let word = cmd.0;
    let domain = ((word >> 48) & 0xFFFF) as u32;
    let value = ((word >> 16) & 0xFFFF_FFFF) as u32;
    let offset = (word & 0xFFFF) as u32;
    (domain, offset, value)
}

pub fn domain_name(domain: u32) -> &'static str {
    use crate::rocket::builders::{
        DOMAIN_CNA, DOMAIN_CORE, DOMAIN_DPU, DOMAIN_DPU_RDMA, DOMAIN_GLOBAL, DOMAIN_PC,
        DOMAIN_PPU, DOMAIN_PPU_RDMA,
    };
    match domain {
        d if d == DOMAIN_CNA => "CNA",
        d if d == DOMAIN_PC => "PC",
        d if d == DOMAIN_CORE => "CORE",
        d if d == DOMAIN_DPU => "DPU",
        d if d == DOMAIN_DPU_RDMA => "DPU_RDMA",
        d if d == DOMAIN_PPU => "PPU",
        d if d == DOMAIN_PPU_RDMA => "PPU_RDMA",
        // DOMAIN_GLOBAL is unconfirmed -- see builders.rs and NOTES.md.
        d if d == DOMAIN_GLOBAL => "GLOBAL?",
        _ => "?",
    }
}

pub fn register_name(offset: u32) -> Option<&'static str> {
    match offset {
        0x0000 => Some("REG_PC_VERSION"),
        0x0004 => Some("REG_PC_VERSION_NUM"),
        0x0008 => Some("REG_PC_OPERATION_ENABLE"),
        0x0010 => Some("REG_PC_BASE_ADDRESS"),
        0x0014 => Some("REG_PC_REGISTER_AMOUNTS"),
        0x0020 => Some("REG_PC_INTERRUPT_MASK"),
        0x0024 => Some("REG_PC_INTERRUPT_CLEAR"),
        0x0028 => Some("REG_PC_INTERRUPT_STATUS"),
        0x002c => Some("REG_PC_INTERRUPT_RAW_STATUS"),
        0x0030 => Some("REG_PC_TASK_CON"),
        0x0034 => Some("REG_PC_TASK_DMA_BASE_ADDR"),
        0x003c => Some("REG_PC_TASK_STATUS"),
        0x1000 => Some("REG_CNA_S_STATUS"),
        0x1004 => Some("REG_CNA_S_POINTER"),
        0x1008 => Some("REG_CNA_OPERATION_ENABLE"),
        0x100c => Some("REG_CNA_CONV_CON1"),
        0x1010 => Some("REG_CNA_CONV_CON2"),
        0x1014 => Some("REG_CNA_CONV_CON3"),
        0x1020 => Some("REG_CNA_DATA_SIZE0"),
        0x1024 => Some("REG_CNA_DATA_SIZE1"),
        0x1028 => Some("REG_CNA_DATA_SIZE2"),
        0x102c => Some("REG_CNA_DATA_SIZE3"),
        0x1030 => Some("REG_CNA_WEIGHT_SIZE0"),
        0x1034 => Some("REG_CNA_WEIGHT_SIZE1"),
        0x1038 => Some("REG_CNA_WEIGHT_SIZE2"),
        0x1040 => Some("REG_CNA_CBUF_CON0"),
        0x1044 => Some("REG_CNA_CBUF_CON1"),
        0x104c => Some("REG_CNA_CVT_CON0"),
        0x1050 => Some("REG_CNA_CVT_CON1"),
        0x1054 => Some("REG_CNA_CVT_CON2"),
        0x1058 => Some("REG_CNA_CVT_CON3"),
        0x105c => Some("REG_CNA_CVT_CON4"),
        0x1060 => Some("REG_CNA_FC_CON0"),
        0x1064 => Some("REG_CNA_FC_CON1"),
        0x1068 => Some("REG_CNA_PAD_CON0"),
        0x1070 => Some("REG_CNA_FEATURE_DATA_ADDR"),
        0x1074 => Some("REG_CNA_FC_CON2"),
        0x1078 => Some("REG_CNA_DMA_CON0"),
        0x107c => Some("REG_CNA_DMA_CON1"),
        0x1080 => Some("REG_CNA_DMA_CON2"),
        0x1084 => Some("REG_CNA_FC_DATA_SIZE0"),
        0x1088 => Some("REG_CNA_FC_DATA_SIZE1"),
        0x1090 => Some("REG_CNA_CLK_GATE"),
        0x1100 => Some("REG_CNA_DCOMP_CTRL"),
        0x1104 => Some("REG_CNA_DCOMP_REGNUM"),
        0x1110 => Some("REG_CNA_DCOMP_ADDR0"),
        0x1140 => Some("REG_CNA_DCOMP_AMOUNT0"),
        0x1144 => Some("REG_CNA_DCOMP_AMOUNT1"),
        0x1148 => Some("REG_CNA_DCOMP_AMOUNT2"),
        0x114c => Some("REG_CNA_DCOMP_AMOUNT3"),
        0x1150 => Some("REG_CNA_DCOMP_AMOUNT4"),
        0x1154 => Some("REG_CNA_DCOMP_AMOUNT5"),
        0x1158 => Some("REG_CNA_DCOMP_AMOUNT6"),
        0x115c => Some("REG_CNA_DCOMP_AMOUNT7"),
        0x1160 => Some("REG_CNA_DCOMP_AMOUNT8"),
        0x1164 => Some("REG_CNA_DCOMP_AMOUNT9"),
        0x1168 => Some("REG_CNA_DCOMP_AMOUNT10"),
        0x116c => Some("REG_CNA_DCOMP_AMOUNT11"),
        0x1170 => Some("REG_CNA_DCOMP_AMOUNT12"),
        0x1174 => Some("REG_CNA_DCOMP_AMOUNT13"),
        0x1178 => Some("REG_CNA_DCOMP_AMOUNT14"),
        0x117c => Some("REG_CNA_DCOMP_AMOUNT15"),
        0x1180 => Some("REG_CNA_CVT_CON5"),
        0x1184 => Some("REG_CNA_PAD_CON1"),
        0x3000 => Some("REG_CORE_S_STATUS"),
        0x3004 => Some("REG_CORE_S_POINTER"),
        0x3008 => Some("REG_CORE_OPERATION_ENABLE"),
        0x300c => Some("REG_CORE_MAC_GATING"),
        0x3010 => Some("REG_CORE_MISC_CFG"),
        0x3014 => Some("REG_CORE_DATAOUT_SIZE_0"),
        0x3018 => Some("REG_CORE_DATAOUT_SIZE_1"),
        0x301c => Some("REG_CORE_CLIP_TRUNCATE"),
        0x4000 => Some("REG_DPU_S_STATUS"),
        0x4004 => Some("REG_DPU_S_POINTER"),
        0x4008 => Some("REG_DPU_OPERATION_ENABLE"),
        0x400c => Some("REG_DPU_FEATURE_MODE_CFG"),
        0x4010 => Some("REG_DPU_DATA_FORMAT"),
        0x4014 => Some("REG_DPU_OFFSET_PEND"),
        0x4020 => Some("REG_DPU_DST_BASE_ADDR"),
        0x4024 => Some("REG_DPU_DST_SURF_STRIDE"),
        0x4030 => Some("REG_DPU_DATA_CUBE_WIDTH"),
        0x4034 => Some("REG_DPU_DATA_CUBE_HEIGHT"),
        0x4038 => Some("REG_DPU_DATA_CUBE_NOTCH_ADDR"),
        0x403c => Some("REG_DPU_DATA_CUBE_CHANNEL"),
        0x4040 => Some("REG_DPU_BS_CFG"),
        0x4044 => Some("REG_DPU_BS_ALU_CFG"),
        0x4048 => Some("REG_DPU_BS_MUL_CFG"),
        0x404c => Some("REG_DPU_BS_RELUX_CMP_VALUE"),
        0x4050 => Some("REG_DPU_BS_OW_CFG"),
        0x4054 => Some("REG_DPU_BS_OW_OP"),
        0x4058 => Some("REG_DPU_WDMA_SIZE_0"),
        0x405c => Some("REG_DPU_WDMA_SIZE_1"),
        0x4060 => Some("REG_DPU_BN_CFG"),
        0x4064 => Some("REG_DPU_BN_ALU_CFG"),
        0x4068 => Some("REG_DPU_BN_MUL_CFG"),
        0x406c => Some("REG_DPU_BN_RELUX_CMP_VALUE"),
        0x4070 => Some("REG_DPU_EW_CFG"),
        0x4074 => Some("REG_DPU_EW_CVT_OFFSET_VALUE"),
        0x4078 => Some("REG_DPU_EW_CVT_SCALE_VALUE"),
        0x407c => Some("REG_DPU_EW_RELUX_CMP_VALUE"),
        0x4080 => Some("REG_DPU_OUT_CVT_OFFSET"),
        0x4084 => Some("REG_DPU_OUT_CVT_SCALE"),
        0x4088 => Some("REG_DPU_OUT_CVT_SHIFT"),
        0x4090 => Some("REG_DPU_EW_OP_VALUE_0"),
        0x4094 => Some("REG_DPU_EW_OP_VALUE_1"),
        0x4098 => Some("REG_DPU_EW_OP_VALUE_2"),
        0x409c => Some("REG_DPU_EW_OP_VALUE_3"),
        0x40a0 => Some("REG_DPU_EW_OP_VALUE_4"),
        0x40a4 => Some("REG_DPU_EW_OP_VALUE_5"),
        0x40a8 => Some("REG_DPU_EW_OP_VALUE_6"),
        0x40ac => Some("REG_DPU_EW_OP_VALUE_7"),
        0x40c0 => Some("REG_DPU_SURFACE_ADD"),
        0x4100 => Some("REG_DPU_LUT_ACCESS_CFG"),
        0x4104 => Some("REG_DPU_LUT_ACCESS_DATA"),
        0x4108 => Some("REG_DPU_LUT_CFG"),
        0x410c => Some("REG_DPU_LUT_INFO"),
        0x4110 => Some("REG_DPU_LUT_LE_START"),
        0x4114 => Some("REG_DPU_LUT_LE_END"),
        0x4118 => Some("REG_DPU_LUT_LO_START"),
        0x411c => Some("REG_DPU_LUT_LO_END"),
        0x4120 => Some("REG_DPU_LUT_LE_SLOPE_SCALE"),
        0x4124 => Some("REG_DPU_LUT_LE_SLOPE_SHIFT"),
        0x4128 => Some("REG_DPU_LUT_LO_SLOPE_SCALE"),
        0x412c => Some("REG_DPU_LUT_LO_SLOPE_SHIFT"),
        0x5000 => Some("REG_DPU_RDMA_RDMA_S_STATUS"),
        0x5004 => Some("REG_DPU_RDMA_RDMA_S_POINTER"),
        0x5008 => Some("REG_DPU_RDMA_RDMA_OPERATION_ENABLE"),
        0x500c => Some("REG_DPU_RDMA_RDMA_DATA_CUBE_WIDTH"),
        0x5010 => Some("REG_DPU_RDMA_RDMA_DATA_CUBE_HEIGHT"),
        0x5014 => Some("REG_DPU_RDMA_RDMA_DATA_CUBE_CHANNEL"),
        0x5018 => Some("REG_DPU_RDMA_RDMA_SRC_BASE_ADDR"),
        0x501c => Some("REG_DPU_RDMA_RDMA_BRDMA_CFG"),
        0x5020 => Some("REG_DPU_RDMA_RDMA_BS_BASE_ADDR"),
        0x5028 => Some("REG_DPU_RDMA_RDMA_NRDMA_CFG"),
        0x502c => Some("REG_DPU_RDMA_RDMA_BN_BASE_ADDR"),
        0x5034 => Some("REG_DPU_RDMA_RDMA_ERDMA_CFG"),
        0x5038 => Some("REG_DPU_RDMA_RDMA_EW_BASE_ADDR"),
        0x5040 => Some("REG_DPU_RDMA_RDMA_EW_SURF_STRIDE"),
        0x5044 => Some("REG_DPU_RDMA_RDMA_FEATURE_MODE_CFG"),
        0x5048 => Some("REG_DPU_RDMA_RDMA_SRC_DMA_CFG"),
        0x504c => Some("REG_DPU_RDMA_RDMA_SURF_NOTCH"),
        0x5064 => Some("REG_DPU_RDMA_RDMA_PAD_CFG"),
        0x5068 => Some("REG_DPU_RDMA_RDMA_WEIGHT"),
        0x506c => Some("REG_DPU_RDMA_RDMA_EW_SURF_NOTCH"),
        0x6000 => Some("REG_PPU_S_STATUS"),
        0x6004 => Some("REG_PPU_S_POINTER"),
        0x6008 => Some("REG_PPU_OPERATION_ENABLE"),
        0x600c => Some("REG_PPU_DATA_CUBE_IN_WIDTH"),
        0x6010 => Some("REG_PPU_DATA_CUBE_IN_HEIGHT"),
        0x6014 => Some("REG_PPU_DATA_CUBE_IN_CHANNEL"),
        0x6018 => Some("REG_PPU_DATA_CUBE_OUT_WIDTH"),
        0x601c => Some("REG_PPU_DATA_CUBE_OUT_HEIGHT"),
        0x6020 => Some("REG_PPU_DATA_CUBE_OUT_CHANNEL"),
        0x6024 => Some("REG_PPU_OPERATION_MODE_CFG"),
        0x6034 => Some("REG_PPU_POOLING_KERNEL_CFG"),
        0x6038 => Some("REG_PPU_RECIP_KERNEL_WIDTH"),
        0x603c => Some("REG_PPU_RECIP_KERNEL_HEIGHT"),
        0x6040 => Some("REG_PPU_POOLING_PADDING_CFG"),
        0x6044 => Some("REG_PPU_PADDING_VALUE_1_CFG"),
        0x6048 => Some("REG_PPU_PADDING_VALUE_2_CFG"),
        0x6070 => Some("REG_PPU_DST_BASE_ADDR"),
        0x607c => Some("REG_PPU_DST_SURF_STRIDE"),
        0x6084 => Some("REG_PPU_DATA_FORMAT"),
        0x60dc => Some("REG_PPU_MISC_CTRL"),
        0x7000 => Some("REG_PPU_RDMA_RDMA_S_STATUS"),
        0x7004 => Some("REG_PPU_RDMA_RDMA_S_POINTER"),
        0x7008 => Some("REG_PPU_RDMA_RDMA_OPERATION_ENABLE"),
        0x700c => Some("REG_PPU_RDMA_RDMA_CUBE_IN_WIDTH"),
        0x7010 => Some("REG_PPU_RDMA_RDMA_CUBE_IN_HEIGHT"),
        0x7014 => Some("REG_PPU_RDMA_RDMA_CUBE_IN_CHANNEL"),
        0x701c => Some("REG_PPU_RDMA_RDMA_SRC_BASE_ADDR"),
        0x7024 => Some("REG_PPU_RDMA_RDMA_SRC_LINE_STRIDE"),
        0x7028 => Some("REG_PPU_RDMA_RDMA_SRC_SURF_STRIDE"),
        0x7030 => Some("REG_PPU_RDMA_RDMA_DATA_FORMAT"),
        0x8000 => Some("REG_DDMA_CFG_OUTSTANDING"),
        0x8004 => Some("REG_DDMA_RD_WEIGHT_0"),
        0x8008 => Some("REG_DDMA_WR_WEIGHT_0"),
        0x800c => Some("REG_DDMA_CFG_ID_ERROR"),
        0x8010 => Some("REG_DDMA_RD_WEIGHT_1"),
        0x8014 => Some("REG_DDMA_CFG_DMA_FIFO_CLR"),
        0x8018 => Some("REG_DDMA_CFG_DMA_ARB"),
        0x8020 => Some("REG_DDMA_CFG_DMA_RD_QOS"),
        0x8024 => Some("REG_DDMA_CFG_DMA_RD_CFG"),
        0x8028 => Some("REG_DDMA_CFG_DMA_WR_CFG"),
        0x802c => Some("REG_DDMA_CFG_DMA_WSTRB"),
        0x8030 => Some("REG_DDMA_CFG_STATUS"),
        0x9000 => Some("REG_SDMA_CFG_OUTSTANDING"),
        0x9004 => Some("REG_SDMA_RD_WEIGHT_0"),
        0x9008 => Some("REG_SDMA_WR_WEIGHT_0"),
        0x900c => Some("REG_SDMA_CFG_ID_ERROR"),
        0x9010 => Some("REG_SDMA_RD_WEIGHT_1"),
        0x9014 => Some("REG_SDMA_CFG_DMA_FIFO_CLR"),
        0x9018 => Some("REG_SDMA_CFG_DMA_ARB"),
        0x9020 => Some("REG_SDMA_CFG_DMA_RD_QOS"),
        0x9024 => Some("REG_SDMA_CFG_DMA_RD_CFG"),
        0x9028 => Some("REG_SDMA_CFG_DMA_WR_CFG"),
        0x902c => Some("REG_SDMA_CFG_DMA_WSTRB"),
        0x9030 => Some("REG_SDMA_CFG_STATUS"),
        0xf008 => Some("REG_GLOBAL_OPERATION_ENABLE"),
        _ => None,
    }
}

/// Prints one line per RegCmd: index, resolved domain name, raw
/// domain/offset/value hex, and resolved register name (or "?" if
/// the offset isn't in rkt_registers.h). Written to stderr so it's
/// visible even if the process later hangs waiting on the NPU.
pub fn dump_cmds(label: &str, cmds: &[RegCmd]) {
    eprintln!("--- regcmd dump: {} ({} entries) ---", label, cmds.len());
    for (i, c) in cmds.iter().enumerate() {
        let (domain, offset, value) = decode(c);
        let dname = domain_name(domain);
        let rname = register_name(offset).unwrap_or("?");
        eprintln!(
            "[{:3}] domain={:<10} (0x{:04x})  off=0x{:04x}  val=0x{:08x}  {}",
            i, dname, domain, offset, value, rname
        );
    }
}
